### ISSUE TITLE
Tworzenie wykresów na podstawie odbieranych danych

### ISSUE THREAD

**Issue by szymonstaron** [prjZsp/programowanieZespolowe#10]

**Comment by szymonstaron** [comment]
Błędne działanie wykresów na środowisku produkcyjnym.
Deadline: 19.05.2017r.

**Comment by Janeed** [comment]
czy po wpisaniu adresu monitora już działa lepiej?

**Comment by Janeed** [comment]
Dobra, powinno już hulać jak burza

**Comment by szymonstaron** [comment]
Próba narysowania wykresu generuje błąd Server connection error, trzeba to poprawić. Swoją drogą, kontrolka Choose monitor jest tam chyba niepotrzebna - każda podstrona powinna sama sobie sprawdzać, jaki monitor jest aktualnie wybrany

**Comment by Janeed** [comment]
Wybór monitora usunięty - teraz jest brany pod uwagę aktualnie wybrany monitor (zapisany w localStorage) - sprawdziłem jeszcze raz - monitor pod adresem 89.79.119.210:1331 działa (trzeba wpisać poprawny port przy adresie)
