### ISSUE TITLE
Przygotowanie listy zadań pozostałych do wykonania w ramach KM2

### ISSUE THREAD

**Issue by tomaszweglinski** [prjZsp/programowanieZespolowe#11]
Lista zadań powinna zostać przekazana team leaderowi w celu rozdysponowania pomiędzy pozostałych członków zespołu.

**Comment by tomaszweglinski** [comment]
1. Monitor przestaje działać po kilku minutach od uruchomienia. Należy zlokalizować przyczynę problemu i usunąć ją. **Rozwiązanie tego problemu jest kluczowe, bo blokuje on dalszą pracę nad projektem**.
2. W tej chwili adres monitora jest whardcode'owany w kilku miejscach (`web\js\sb-admin-2.js`, `web\js\graphsPage\graphsPage.js`), co utrudnia jego edytowanie (chociażby w czasie testów). Ponieważ w przyszłości i tak będzie potrzebna dynamiczna lista monitorów, należy stworzyć jakiś mechanizm z funkcjami do dodawania, przeglądania i usuwania monitorów z listy. Ponieważ specyfikacja nie określa, jak dokładnie ma to być zrealizowane, najprościej byłoby napisać zwykły skrypt, który przechowuje te dane lokalnie, w przeglądarce (np. za pomocą obiektu `localStorage` z HTML5). Każdy monitor ma być reprezentowany przez dwie zmienne: nazwa (nadana przez użytkownika przy dodawaniu) i adres IP.
3. Po wykonaniu poprzedniego zadania należy zaktualizować tabelę w zakładce _Monitors_. Powinna mieć 3 kolumny: _Name_, _IP Address_ i _Options_, a także wyświetlać rzeczywistą listę monitorów. W opcjach powinien znajdować się na razie tylko przycisk _Remove_, który usuwa monitor z pamięci przeglądarki oraz z GUI. Analogicznie formularz dodawania powinien mieć 2 pola: _Name_ i _IP Address_.
4. Formularze dodawania monitorów, filtrowania hostów, zasobów itd. są "przyklejone" do znajdujących się pod nimi tabel, co trochę rzuca się w oczy. Dobrze byłoby zrobić między nimi niewielki odstęp.
5. Identyfikator sensora nie powinien być przez niego generowany losowo, ale zapisany na stałe w pliku konfiguracyjnym. Identyfikatorem takim może być np. pseudolosowy ciąg znaków wygenerowany za pomocą jakiegoś zewnętrznego narzędzia; coś w rodzaju `b293f253-8f34-48c9-ad85-680fce16a6ce` z [Online UUID Generator Tool](https://www.uuidgenerator.net/).

**Comment by AWisniowski** [comment]
#1 Poprawione, dodałem obsługę błędów do listener'a w monitorze, teraz
zamiast ubijać apke będą się wypluwać do logów. Aktualnie są to jedynie
błędy związane z zerwaniem połączenia między sensorem a monitorem więc nie
trzeba ich obsługiwać w żaden inny sposób.

W dniu 18 maja 2017 13:22 użytkownik tomaszweglinski <
notifications@github.com> napisał:

**Comment by szymonstaron** [comment]
6. Integracja poszczególnych modułów (ręczne testy integracyjne) - uruchomienie sensorów, monitorów, klienta, sprawdzenie poprawności.
7. Usprawnienie procesu budowania i uruchamiania aplikacji po zmianach w kodzie (repozytorium) - wykorzystanie np. Jenkinsa

**Comment by szymonstaron** [comment]
Deadline: 20.05.2017r.

**Comment by tomaszweglinski** [comment]
8. Skrypty wspomniane w zadaniu 2 należy przerobić w taki sposób, aby korzystały w aktualnie wybranego monitora.
9. Wpisy w zakładce _Hosts_ powinny być linkami, które przenoszą do strony _Resources_, odfiltrowanej dla wybranego hosta.
10. Filtrowanie hostów nie działa prawidłowo. Jeżeli wpiszemy tam np. `ox`, to wyświetlą nam się wyniki, mimo, że żaden host nie ma w swojej nazwie takiego ciągu znaków.
11. Wydaje mi się, że zaszło nieporozumienie odnośnie znaczenia słowa zasób (resource). W specyfikacji sensora napisane jest _"Przykład zasobu i metryki: Host / CPU Utilization (aktualne zużycie CPU dla hosta)"_ co sugeruje, że zasób = host. Z takim założeniem też napisane zostało REST API, gdzie w opisie [GET /measurements](https://github.com/prjZsp/programowanieZespolowe/wiki/REST-API#get-measurements) nie ma czegoś takiego jak nazwa hosta, bo od tego jest właśnie nazwa zasobu. Trzeba poprawić RESTa w taki sposób, żeby w `resource` była zwracana właśnie nazwa hosta.
12. Z tabeli w zakładce _Resources_ należy usunąć kolumnę _Id_, ponieważ ID nie powinny być widoczne dla użytkowników. Dostęp do pomiarów z danego sensora powinien odbywać się np. poprzez kliknięcie w przycisk w kolumnie _Actions_, który po prostu przenosiłby do odpowiedniej strony z pomiarami. Przy okazji przyciski _Edit_ i _Remove_ można usunąć, bo wpisy w tej tabeli nie są edytowalne.
13. Próba narysowania wykresu generuje błąd `Server connection error`, trzeba to poprawić. Swoją drogą, kontrolka _Choose monitor_ jest tam chyba niepotrzebna - każda podstrona powinna sama sobie sprawdzać, jaki monitor jest aktualnie wybrany.
