### ISSUE TITLE
Monitor przestaje działać po kilku minutach od uruchomienia.

### ISSUE THREAD

**Issue by szymonstaron** [prjZsp/programowanieZespolowe#12]
Monitor przestaje działać po kilku minutach od uruchomienia. Należy zlokalizować przyczynę problemu i usunąć ją. Rozwiązanie tego problemu jest kluczowe, bo blokuje on dalszą pracę nad projektem.

**Comment by AWisniowski** [comment]
Fixed: https://github.com/pawellll/programowanieZespolowe/commit/388e655eb31812ec8383a5a2af60c6ad59bdc33e
