### ISSUE TITLE
Stworzenie mechanizmu do dodawania, przeglądania i usuwania monitorów z listy.

### ISSUE THREAD

**Issue by szymonstaron** [prjZsp/programowanieZespolowe#13]
W tej chwili adres monitora jest whardcode'owany w kilku miejscach (web\js\sb-admin-2.js, web\js\graphsPage\graphsPage.js), co utrudnia jego edytowanie (chociażby w czasie testów). Ponieważ w przyszłości i tak będzie potrzebna dynamiczna lista monitorów, należy stworzyć jakiś mechanizm z funkcjami do dodawania, przeglądania i usuwania monitorów z listy. Ponieważ specyfikacja nie określa, jak dokładnie ma to być zrealizowane, najprościej byłoby napisać zwykły skrypt, który przechowuje te dane lokalnie, w przeglądarce (np. za pomocą obiektu localStorage z HTML5). Każdy monitor ma być reprezentowany przez dwie zmienne: nazwa (nadana przez użytkownika przy dodawaniu) i adres IP.

**Comment by szymonstaron** [comment]
Deadline: 22.05.2017r.

**Comment by Janeed** [comment]
Dodałem jako takie zarządzanie monitorami (po stronie klienta, localStorage).
Można dodawać/usuwać/ustawiać jako domyślny
Po stronie wykresów dodałem możliwość wyboru (inaczej wybierany jest ten domyślny)
