### ISSUE TITLE
Zaktualizowanie tabeli w zakładce Monitors.

### ISSUE THREAD

**Issue by szymonstaron** [prjZsp/programowanieZespolowe#14]
Tabela powinna mieć 3 kolumny: Name, IP Address i Options, a także wyświetlać rzeczywistą listę monitorów. W opcjach powinien znajdować się na razie tylko przycisk Remove, który usuwa monitor z pamięci przeglądarki oraz z GUI. Analogicznie formularz dodawania powinien mieć 2 pola: Name i IP Address.

**Comment by szymonstaron** [comment]
Deadline: 21.05.2017r.

**Comment by karolpl** [comment]
Dodano nowe kolumny do tabeli oraz zmodyfikowano formularz dodawania monitora. Przycisk Remove usuwa monitor, a Select wybiera aktualny monitor.
