### ISSUE TITLE
Drobne poprawki w GUI

### ISSUE THREAD

**Issue by szymonstaron** [prjZsp/programowanieZespolowe#15]
Formularze dodawania monitorów, filtrowania hostów, zasobów itd. są "przyklejone" do znajdujących się pod nimi tabel, co trochę rzuca się w oczy. Dobrze byłoby zrobić między nimi niewielki odstęp.

**Comment by szymonstaron** [comment]
Deadline: 21.05.2017r.

**Comment by karolpl** [comment]
Poprawki wprowadzone
