### ISSUE TITLE
Tworzenie Identyfikatora zasobu w sensorze

### ISSUE THREAD

**Issue by szymonstaron** [prjZsp/programowanieZespolowe#16]
Identyfikator zasobu w sensorze nie powinien być przez niego generowany losowo, ale zapisany na stałe w pliku konfiguracyjnym. Identyfikatorem takim może być np. pseudolosowy ciąg znaków wygenerowany za pomocą jakiegoś zewnętrznego narzędzia; coś w rodzaju b293f253-8f34-48c9-ad85-680fce16a6ce z Online UUID Generator Tool.

**Comment by szymonstaron** [comment]
Deadline: 22.05.2017r.

**Comment by Endriu93** [comment]
Obecnie za zapewnienie unikatowego identyfikatora zasobu odpowiedzialny jest użytkownik uruchamiający sensor.
W tym celu należy wygenerować unikatowe id (np. korzystając z następującego narzędzia: https://www.uuidgenerator.net/ ) oraz wstawić w pliku konfiguracyjnym w właściwości: "resourceId"

**Comment by szymonstaron** [comment]
Andrzej, chodzi właśnie o to, żeby to sensor był za to odpowiedzialny, a nie uruchamiający go użytkownik. Niech  sensor sprawdza, czy w pliku konfiguracyjnym ma wpisany identyfikator i wygeneruje go w przypadku jego braku (pierwsze uruchomienie). Dzięki!

**Comment by Endriu93** [comment]
Wprowadzono zmiany opisane w powyższym komentarzy.
Obecnie w pliku konfiguracyjnym nie deklarujemy właściwości "resourceId", zostanie wygenerowana przez sensor przy pierwszym uruchomieniu sensora.
