### ISSUE TITLE
Usprawnienie procesu budowania i uruchamiania aplikacji

### ISSUE THREAD

**Issue by szymonstaron** [prjZsp/programowanieZespolowe#19]
Usprawnienie procesu budowania i uruchamiania aplikacji po zmianach w kodzie (repozytorium) - wykorzystanie np. Jenkinsa.

**Comment by szymonstaron** [comment]
Deadline: 21.05.2017r.

**Comment by AWisniowski** [comment]
Jenkins dostępny pod adresem http://89.79.119.210:1332
Automatycznie aktualizujący środowisko produkcyjne po zmianach w gałęzi master

login;pass: pz2017;pz2017
