### ISSUE TITLE
Obsługa wielu monitorów

### ISSUE THREAD

**Issue by szymonstaron** [prjZsp/programowanieZespolowe#20]
Skrypty wspomniane w zadaniu 2 (patrz niżej) należy przerobić w taki sposób, aby korzystały w aktualnie wybranego monitora.

Zadanie2:
W tej chwili adres monitora jest whardcode'owany w kilku miejscach (web\js\sb-admin-2.js, web\js\graphsPage\graphsPage.js), co utrudnia jego edytowanie (chociażby w czasie testów). Ponieważ w przyszłości i tak będzie potrzebna dynamiczna lista monitorów, należy stworzyć jakiś mechanizm z funkcjami do dodawania, przeglądania i usuwania monitorów z listy. Ponieważ specyfikacja nie określa, jak dokładnie ma to być zrealizowane, najprościej byłoby napisać zwykły skrypt, który przechowuje te dane lokalnie, w przeglądarce (np. za pomocą obiektu localStorage z HTML5). Każdy monitor ma być reprezentowany przez dwie zmienne: nazwa (nadana przez użytkownika przy dodawaniu) i adres IP.

**Comment by Janeed** [comment]
To chyba do zamknięcia? graphsPage.js korzysta już z aktualnie wybranego monitora.

**Comment by szymonstaron** [comment]
Janku fakt, ale  jest on whardkowany w innym miejscu, należy zaimplementować możliwość dodawania nowych monitorów do listy.

**Comment by tomaszweglinski** [comment]
W tej chwili zostało już chyba tylko zaktualizowanie skryptu `sb-admin-2.js`, reszta wydaje się działać. Przy okazji dodam, że adres IP monitorów prawdopodobnie będzie musiał być zapisywany razem z portem, na jakim monitor działa - innymi słowy, raczej nie będzie tak, że używany jak na razie port 1331 będzie uniwersalny dla wszystkich monitorów, bo jeśli uruchomimy je wszystkie na jednym serwerze, to każdemu będzie siłą rzeczy trzeba przypisać inny port.

**Comment by Janeed** [comment]
Issue było nieprzydzielne, więc na siebie przepiąłem.

Wywaliłem zakodowane adresy, trochę tam było pomieszane, że np. z resource jak się chciało przejść na graphs to przekierowywało zawsze na http://89.79.119.210:1330 (nawet jak się odpalało lokalnie stronę)

Rzućcie okiem czy czegoś nie przeoczyłem :)

PS. Dodałem informowanie użytkownika o braku aktualnie wybranego monitora, żeby nie było sytuacji, że nie działa i nie wiadomo dlaczego :)

**Comment by tomaszweglinski** [comment]
Wszystko wydaje się działać, zamykam.
