### ISSUE TITLE
Podlinkowanie wpisów w zakładce Hosts

### ISSUE THREAD

**Issue by szymonstaron** [prjZsp/programowanieZespolowe#21]
Wpisy w zakładce Hosts powinny być linkami, które przenoszą do strony Resources, odfiltrowanej dla wybranego hosta.

**Comment by szymonstaron** [comment]
Deadline: 22.05.2017r.

**Comment by karolpl** [comment]
Dodano linki do strony Resources dla wybranego hosta.
