### ISSUE TITLE
Filtrowanie hostów nie działa prawidłowo.

### ISSUE THREAD

**Issue by szymonstaron** [prjZsp/programowanieZespolowe#22]
Filtrowanie hostów nie działa prawidłowo. Jeżeli wpiszemy tam np. ox, to wyświetlą nam się wyniki, mimo, że żaden host nie ma w swojej nazwie takiego ciągu znaków.

**Comment by szymonstaron** [comment]
Deadline: 22.05.2017r.

**Comment by karolpl** [comment]
Błąd filtrowania do sprawdzenia po stronie monitora
