### ISSUE TITLE
Poprawki do tabeli resources

### ISSUE THREAD

**Issue by szymonstaron** [prjZsp/programowanieZespolowe#24]
Z tabeli w zakładce Resources należy usunąć kolumnę Id, ponieważ ID nie powinny być widoczne dla użytkowników. Dostęp do pomiarów z danego sensora powinien odbywać się np. poprzez kliknięcie w przycisk w kolumnie Actions, który po prostu przenosiłby do odpowiedniej strony z pomiarami. Przy okazji przyciski Edit i Remove można usunąć, bo wpisy w tej tabeli nie są edytowalne.

**Comment by szymonstaron** [comment]
Deadline: 22.05.2017r.

**Comment by karolpl** [comment]
Usunięto kolumnę Id z tabeli oraz dodano przekierowanie do pomiarów dotyczących zasobu
