### ISSUE TITLE
Stworzenie strony powitalnej (index.html)

### ISSUE THREAD

**Issue by szymonstaron** [prjZsp/programowanieZespolowe#25]
Aktualnie strona index.html zawiera przykładowe wykresy. Należy je usunąć i wstawić krótką notkę informacyjną  (zawrzeć np. informacje z git-wiki), w paru zdaniach opisać co strona zawiera.

Deadline: 31.05.2017r.

**Comment by karolpl** [comment]
Dodana zawartość strony index.html
