### ISSUE TITLE
Przygotowanie listy zadań do wykonania w ramach KM3 

### ISSUE THREAD

**Issue by szymonstaron** [prjZsp/programowanieZespolowe#27]
Deadline: 28.05.2017r.

**Comment by szymonstaron** [comment]
1. Strona powitalna.
2. Poprawki do wykresów (zwiększenie domyślnego okienka czasowego, możliwość jego dostosowania).

**Comment by tomaszweglinski** [comment]
## Wysoki priorytet
3. Stworzenie mechanizmu rejestrowania / logowania użytkowników. Rejestracja może być maksymalnie prosta i ograniczać się do podania nazwy użytkownika i hasła, a do logowania można wykorzystać np. Basic Auth. Mechanizm ten będzie wykorzystywany głównie przy zapytaniach RESTowych (patrz zad. 4).
4. Zaimplementowanie zapytań [POST /measurements](https://github.com/prjZsp/programowanieZespolowe/wiki/REST-API#post-measurements) i [DELETE /measurements/{id}](https://github.com/prjZsp/programowanieZespolowe/wiki/REST-API#delete-measurementsid). Ponieważ obydwa wymagają uwierzytelniania (pierwsze, żeby było wiadomo, kto jest autorem pomiaru złożonego, a drugie, żeby sprawdzić, czy ma uprawnienia do jego usunięcia) zadanie to musi zostać wykonane równolegle z poprzednim.

## Średni priorytet
5. Napisanie klienta automatycznego (zgodnie z wymaganiem nr 10 ze specyfikacji).

## Niski priorytet
6. Filtrowanie w zakładkach _Hosts_ i _Resources_ powinno być case insensitive.

**Comment by tomaszweglinski** [comment]
7. Wykonanie GUI pozwalającego na dodawanie i usuwanie pomiarów złożonych. W zakładce _Resources_,
w kolumnie _Action_, w zależności od tego, czy dany pomiar jest złożony, czy nie (parametr `isComposite`
w odpowiedzi RESTa), należy dodać odpowiedni przycisk:
- _Add composite_ (jeśli dany pomiar jest prosty),
- _Remove_ (jeśli dany pomiar jest złożony).

    Przycisk do usuwania oczywiście usuwa dany pomiar, a przycisk dodawania przenosi do nowej strony,
na której możemy określić:
- jego nazwę,
- okres, jaki będzie brany pod uwagę przy dokonywaniu pomiaru (wyrażony w sekundach),
- odstęp między kolejnymi pomiarami (wyrażony w sekundach).

**Comment by tomaszweglinski** [comment]
8. Dodanie możliwości przeglądania archiwalnych danych. Jak na razie możliwe jest przeglądanie wyłącznie najnowszych pomiarów i wykresów, a użytkownik powinien też mieć możliwość oglądania danych z jakiegoś wybranego okresu. W tym celu zarówno na stronie z pomiarami, jak i stronie z wykresami, powinny znaleźć się dodatkowe formularze, pozwalające na określenie przedziału czasowego. Czyli np. na stronie z pomiarami, w miejscu, gdzie obecnie znajduje się panel _Select measurement_, powinny znaleźć się 2 panele: _Recent measurements_ (czyli to, co dotychczas, gdzie podajemy tylko liczbę pomiarów) i _Archival measurements_ (w którym określamy ramy czasowe). Ponadto w przypadku wykresów, jeżeli dany wykres prezentuje dane archiwalne, to nie powinien być odświeżany.
9. Drobne zmiany w GUI:
- Zmienić napis "Monitor [Name]" w lewym górnym rogu na "System for monitoring distributed computer resources".
- Usunąć zakładki _Measurements_, _Graphs_ i _Measurements archive_ oraz odpowiadające im wpisy na stronie głównej.
- Podzielić stronę z grafami na takie panele, jakie są używane np. na stronie z pomiarami.
10. Kiedy cały projekt zostanie już zatwierdzony przez liderów, przygotować:
a) Pakiet instalacyjny systemu razem z podręcznikiem instalacji.
b) Podręcznik użytkownika (ten podpunkt może być dla mnie).
