### ISSUE TITLE
Poprawki do wykresów.

### ISSUE THREAD

**Issue by szymonstaron** [prjZsp/programowanieZespolowe#28]
1.  Usunąć pole 'resource name' - do wykresów wchodzimy zawsze korzystając z linku w zakładce resources.
2. Dodać obsługę 'limit' - aktualnie nie działa (wymaga podania resource name, powinno aplikować do aktualnie wybranego).
3. Zwiększyć domyślne okienko czasowe (limit) - np. do 5 minut (czas odswieżania 5 sekund może zostać).

**Comment by szymonstaron** [comment]
Deadline: 31.05.2017r.

**Comment by tomaszweglinski** [comment]
4. Etykiety na osi poziomej powinny zawierać czas zapisany w jakimś czytelnym dla człowieka formacie.
5. Aktualizowanie wykresu w regularnych odstępach ma dawać, na ile to możliwe, wrażenie jego przesuwania. Dlatego kiedy pkt. 3 zostanie już wykonany, korzystne może się okazać usunięcie "animacji" wykonywanej po zaktualizowaniu wykresu, żeby nie wyglądało to tak, jakby wykres ciągle podnosił się z poziomu zerowego.

**Comment by Janeed** [comment]
Zrobione, do weryfikacji

**Comment by szymonstaron** [comment]
Dzięki, wygląda super, może jeszcze taka drobnostka to w polu do wprowadzenia limitu dopisac [sec] żeby była jasność co do jednostek :)

**Comment by Janeed** [comment]
Ok, usunąłem '(optional)' bo brzydko to wyglądało z dopisaną jednostką.
Zamykam
