### ISSUE TITLE
Mechanizm rejestrowania / logowania użytkowników.

### ISSUE THREAD

**Issue by szymonstaron** [prjZsp/programowanieZespolowe#29]
Stworzenie mechanizmu rejestrowania / logowania użytkowników. Rejestracja może być maksymalnie prosta i ograniczać się do podania nazwy użytkownika i hasła, a do logowania można wykorzystać np. Basic Auth. Mechanizm ten będzie wykorzystywany głównie przy zapytaniach RESTowych.
Deadline:  31.05.2017r.

**Comment by kamil-nowak** [comment]
Dodałem dziś w pełni działającą wersję serwisu do zarządzania użytkownikami, który pozwala restowo dodawać nowych użytkowników, sprawdzać czy użytkownik istnieje (logowanie) oraz dodatkowo wyświetlać wszystkich użytkowników i ich usuwać (było to przydatne podczas prac nad serwisem i póki co zostało). Autoryzacja jest oparta zgodnie z propozycją na mechanizmie Basic Auth.
 
Dokumentacja do tej części pojawi się dziś, póki co plik curlExamples.txt zawiera rozbudowane przykłady. Funkcjonalnie wszystko działa od tej strony więc zostaje dodanie po stronie GUI logowania i rejestracji nowych użytkowników.

**Comment by kamil-nowak** [comment]
Dokumentacja api restowego serwisu już w wiki. https://github.com/prjZsp/programowanieZespolowe/wiki/Credentials-Service-REST-API. Andrzej wrzucił już też zmiany po stronie gui, lokalnie u nas już większość działa, jeszcze pare drobnostek i można testować wszystko razem .
