### ISSUE TITLE
GUI - dodawanie/usuwanie pomiarów złożonych

### ISSUE THREAD

**Issue by szymonstaron** [prjZsp/programowanieZespolowe#33]
Wykonanie GUI pozwalającego na dodawanie i usuwanie pomiarów złożonych. W zakładce Resources,
w kolumnie Action, w zależności od tego, czy dany pomiar jest złożony, czy nie (parametr isComposite
w odpowiedzi RESTa), należy dodać odpowiedni przycisk:
- Add composite (jeśli dany pomiar jest prosty),
- Remove (jeśli dany pomiar jest złożony).

Przycisk do usuwania oczywiście usuwa dany pomiar, a przycisk dodawania przenosi do nowej strony,
na której możemy określić:
- jego nazwę,
- okres, jaki będzie brany pod uwagę przy dokonywaniu pomiaru (wyrażony w sekundach),
- odstęp między kolejnymi pomiarami (wyrażony w sekundach).

Deadline: 04.06.2017r.

**Comment by kamil-nowak** [comment]
Tutaj jeszcze pamiętajcie że dodawanie i usuwanie pomiarów złożonych zgodnie z dokumentacją REST API monitora wymaga uwierzytelnienia basic auth, więc należy zadbać, żeby to przekazać.
