### ISSUE TITLE
Przeglądanie archiwalnych danych.

### ISSUE THREAD

**Issue by szymonstaron** [prjZsp/programowanieZespolowe#35]
Dodanie możliwości przeglądania archiwalnych danych. Jak na razie możliwe jest przeglądanie wyłącznie najnowszych pomiarów i wykresów, a użytkownik powinien też mieć możliwość oglądania danych z jakiegoś wybranego okresu. W tym celu zarówno na stronie z pomiarami, jak i stronie z wykresami, powinny znaleźć się dodatkowe formularze, pozwalające na określenie przedziału czasowego. Czyli np. na stronie z pomiarami, w miejscu, gdzie obecnie znajduje się panel Select measurement, powinny znaleźć się 2 panele: Recent measurements (czyli to, co dotychczas, gdzie podajemy tylko liczbę pomiarów) i Archival measurements (w którym określamy ramy czasowe). Ponadto w przypadku wykresów, jeżeli dany wykres prezentuje dane archiwalne, to nie powinien być odświeżany.

Janek - do Ciebie to ostatnie zdanie :)

Deadline:  05.06.2017r.

**Comment by Janeed** [comment]
Panel dodany, nie miałem jak go przetestować jeszcze bo coś się popsuło w monitorach
