### ISSUE TITLE
Podręcznik użytkownika

### ISSUE THREAD

**Issue by szymonstaron** [prjZsp/programowanieZespolowe#37]
DOPIERO PO ZAKOŃCZENIU POZOSTAŁYCH ZADAŃ

Deadline:  07.06.2017r.

**Comment by tomaszweglinski** [comment]
Podręcznik został dodany do [Wiki](https://github.com/prjZsp/programowanieZespolowe/wiki/Podr%C4%99cznik-u%C5%BCytkownika).
